import {StyleSheet, Dimensions, Platform} from 'react-native';
import {getStatusBarHeight} from '../../common';

const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    zIndex: 1,
    paddingTop: Platform.OS !== 'ios' ? getStatusBarHeight() : 0,
    paddingHorizontal: 16,
  },
  header: {
    paddingTop: Platform.OS === 'ios' ? getStatusBarHeight() : 0,
    marginTop: 20,
    // paddingHorizontal: 16,
  },
  header1: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
  },
  title: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 24,
    lineHeight: 36,
    flex: 1,
    textAlign: 'center',
  },
  thumbnail: {
    width: '100%',
    height: deviceWidth * 0.8,
    resizeMode: 'contain',
    borderRadius: 16,
  },
  image: {
    width: '25%',
    height: 82,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  element: {
    width: '25%',
    height: 82,
    resizeMode: 'contain',
    borderRadius: 8,
  },
  infoWrapper: {
    marginTop: 16,
    backgroundColor: '#ebf7ff',
    borderRadius: 12,
    padding: 16,
  },
  infoTitle: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 20,
    color: '#0B2337',
    width: '85%',
  },
  infoCate: {
    marginTop: 8,
    fontFamily: 'Inter-Regular',
    fontSize: 13,
    color: '#0B2337',
  },
  price: {
    marginTop: 8,
    fontFamily: 'Inter-SemiBold',
    fontSize: 30,
    color: '#25C2E8',
    fontWeight: '500',
  },
  rate: {
    backgroundColor: '#1180C3',
    borderRadius: 4,
    padding: 4,
    fontSize: 12,
    color: '#fff',
  },
  reviews: {
    fontSize: 14,
    color: '#0B2337',
  },
  availability: {
    marginTop: 4,
    fontSize: 14,
    color: '#0B2337',
  },
  stock: {
    marginTop: 8,
    backgroundColor: '#F1673A',
    borderRadius: 4,
    padding: 4,
    width: 65,
    textAlign: 'center',
    fontSize: 12,
    color: '#fff',
  },
  unlimited: {
    marginTop: 8,
    backgroundColor: '#12c918',
    borderRadius: 4,
    padding: 4,
    width: 100,
    textAlign: 'center',
    fontSize: 12,
    color: '#fff',
  },
  btnSubmit: {
    marginTop: 16,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  txtSubmit: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#fff',
  },
  tab: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 16,
    color: '#0B2337',
    paddingHorizontal: 8,
  },
  activeTab: {
    borderColor: '#1180C3',
    height: 2,
    marginTop: 4,
  },
  avatar: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    borderRadius: 20,
  },
  reviewWrapper: {
    marginBottom: 8,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  description: {
    marginTop: 8,
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: '#314753',
  },
  reviewTitle: {
    fontFamily: 'Inter-Medium',
    fontSize: 16,
    color: '#0B2337',
  },
  quality: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: '#0B2337',
    textAlign: 'center',
  },
  btnReview: {
    marginTop: 16,
    marginBottom: 16,
    width: 120,
    height: 42,
    backgroundColor: '#1180C3',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  txtReview: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#fff',
  },
  iconBack: {
    height: 14,
    width: 14,
    resizeMode: 'contain',
    tintColor: '#000',
  },
  txt3: {
    fontFamily: 'Inter-SemiBold',
    fontSize: 18,
    // lineHeight: 18,
    marginLeft: 6,
    color: '#314753',
  },
  txt2: {
    fontFamily: 'Inter-Regular',
    fontSize: 15,
    lineHeight: 18,
    color: '#F11616',
  },
  icon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  iconShare: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  iconDown: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  content: {
    fontFamily: 'Inter-Regular',
    fontSize: 18,
    // lineHeight: 18,
    color: '#939393',
  },
  expireWrapper: {
    padding: 4,
    borderRadius: 4,
    backgroundColor: '#fff',
    opacity: 0.8,
  },
  expireText: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: '#314753',
  },
  share: {
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    color: '#0B2337',
  },
  contentWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  contentText: {
    flex: 1,
    fontFamily: 'Inter-Regular',
    fontSize: 14,
    lineHeight: 20,
    color: '#4E4E4E',
  },
});
