import {StyleSheet, Dimensions} from 'react-native';

const deviceWidth = Dimensions.get('window').width;
const deviceHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  container: {
    backgroundColor: '#F1673A',
    flex: 1,
  },
  imgBanner: {
    width: (986 / 1179) * deviceWidth,
    height: (986 / 1179) * deviceWidth,
    backgroundColor: '#ffffff',
    opacity: 0.2,
    borderRadius: 99999,
    position: 'absolute',
    right: '-42%',
  },
  wrapper: {
    position: 'relative',
    flex: 1,
    marginTop: 40,
    backgroundColor: '#ffffff',
    borderTopLeftRadius: (215 / 1179) * deviceWidth,
  },
  imgBottom: {
    marginTop: 10,
    resizeMode: 'contain',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  textBottom: {
    marginTop: 40,
    fontSize: 14,
    color: '#000',
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
  },
  logo: {
    height: (190 / 1179) * deviceWidth,
    width: (399 / 1179) * deviceWidth,
    resizeMode: 'contain',
    // position: "absolute",
  },
  viewLogo: {
    alignSelf: 'center',
    zIndex: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    marginTop: 32,
    textAlign: 'center',
    fontSize: 28,
    fontFamily: 'Inter-SemiBold',
  },
  containerImg: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  text: {
    fontSize: 15,
    color: '#000',
  },
  textInput: {
    flex: 1,
    height: 52,
    color: '#000',
    fontFamily: 'Inter-Regular',
    fontSize: 14,
  },
  icEnter: {
    width: 17,
    height: 17,
    resizeMode: 'contain',
  },
  button: {
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 1,
    top: deviceHeight / 2 - 20,
  },
  nextButton: {
    height: (264 / 375) * deviceWidth,
    width: (264 / 375) * deviceWidth,
    resizeMode: 'contain',
  },
  iconBack: {
    height: 22,
    width: 22,
    resizeMode: 'contain',
  },
  txtAccept: {
    fontFamily: 'Inter-Regular',
    fontSize: 13,
    color: '#9E9E9E',
  },
  iconCheck: {
    fontSize: 22,
    color: '#9E9E9E',
    marginRight: 12,
  },
  btnSubmit: {
    marginTop: 0,
    flex: 1,
    height: 60,
    backgroundColor: '#1180C3',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 36,
  },
  txtSubmit: {
    fontFamily: 'Inter-Regular',
    fontSize: 16,
    color: '#fff',
  },
  line: {
    width: 90,
    height: 1,
    backgroundColor: '#DBDBDB',
  },
  iconFacebook: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  iconTwitter: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  iconGoogle: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  txtForgot: {
    marginTop: 24,
    fontFamily: 'Inter-Regular',
    textAlign: 'center',
    fontSize: 15,
    color: '#F32626',
  },
  registerWrapper: {
    marginTop: 48,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  txtYet: {
    fontFamily: 'Inter-Regular',
    fontSize: 15,
    color: '#000000',
    marginRight: 6,
  },
  txtRegister: {
    fontFamily: 'Inter-Regular',
    fontSize: 15,
    color: '#1180C3',
  },
  viewLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 250,
    alignSelf: 'center',
    marginTop: 71,
  },
  viewButton: {
    marginTop: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: 120,
    alignSelf: 'center',
  },
  viewInput: {
    flex: 1,
    color: '#000',
    backgroundColor: '#F3F3F3',
    borderRadius: 4,
    marginBottom: 16,
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',

    borderWidth: 2,
    borderColor: '#F3F3F3',
  },
  bottomLeftBackground: {
    width: (986 / 1179) * deviceWidth,
    height: (986 / 1179) * deviceWidth,
    backgroundColor: '#FFC224',
    opacity: 0.2,
    borderRadius: 99999,
    position: 'absolute',
    left: 0,
    bottom: '-30%',
  },
  rightBottomBackground: {
    width: (695 / 1179) * deviceWidth,
    height: (695 / 1179) * deviceWidth,
    resizeMode: 'contain',
    position: 'absolute',
    right: '-20%',
    bottom: '-12%',
  },
});
